### PR TITLE
Added support for loading configurations from URLs

### PR DESCRIPTION
**Pull request by BartoszKaszewczuk**
Added support for loading configurations from URLs along with necessary tests.

### CODE REVIEW

**Comment by pmwmedia** [comment]
I like it! Thanks for the documented and tested code.

**Comment by BartoszKaszewczuk** [comment]
Always happy to contribute. 
Do you have a date in mind for 1.2 release?

**Comment by pmwmedia** [comment]
I will release 1.2 RC1 in November. The first release candidate, for which no bugs will be reported, will be published as final version 1.2.  So, I guess the final version 1.2 will be published in December or January.

**Comment by BartoszKaszewczuk** [comment]
Brilliant. Can't wait to update my project and make use of new features.

**Pull request merged**
