### PR TITLE
Add Schema-Name as param to JdbcWriter.java

### PR DESCRIPTION
**Pull request by ghost**
to specify a different one than the default.

### Description

Linked issue: #243

### Definition of Done

- [x] I read [contributing.md](https://github.com/tinylog-org/tinylog/blob/v2.4/contributing.md)
- [x] There are no TODOs left in the code
- [x] Code style follows the tinylog standard
- [x] All classes and methods have Javadoc
- [x] Changes are covered by JUnit tests including edge cases, errors, and exception handling
- [x] Maven build works including compiling, tests, and checks (`mvn verify`)
- [x] Changes are committed by a verified email address that is assigned to the GitHub account (https://github.com/settings/emails)

### Documentation

Additions or amendments for the [public documentation](https://github.com/tinylog-org/tinylog/wiki/Documentation):

```markdown

```

### Agreements

- [x] I agree that my changes will be published under the terms of the [Apache License 2.0](https://github.com/tinylog-org/tinylog/blob/v2.0/license.txt) (mandatory)
- [x] I agree that my GitHub user name will be published in the release notes (optional)

### CODE REVIEW

**Comment by ghost** [comment]
One could also include the new parameter in the JDBC Writer Section of this page https://tinylog.org/v2/configuration/ 
Something like:
```writer.schema           = monitoring                         # optional, if not default```

**Comment by ghost** [comment]
I don't think, that any tests are necessary for this change.

**Comment by pmwmedia** [comment]
> I don't think, that any tests are necessary for this change.

Even the change is quite small, one JUnit test would be great to ensure that it's working with H2.

**Comment by ghost** [comment]
Ok, I added a test case.
I have also tested the change in one of my apps, and it runs great.
Do you have any plans for the release of 2.5?

**Comment by pmwmedia** [comment]
Thank you very much for your contribution!

tinylog 2.5 M1 is ready to be released. I just need to find a couple of hours for writing the documentation and the news post.

**Pull request merged**
