### PR TITLE
#111 - Adding SeverityLevelIntegerToken and its test for being able t…

### PR DESCRIPTION
**Pull request by sezinkarli**
#111 implemented

### CODE REVIEW

**Comment by pmwmedia** [comment]
Thank you very much for your awesome pull request! I really know the appreciate that you even added JUnit tests and Javadoc documentation :)

May I ask just two little changes:

1) Could you verify the hard coded integer values for the levels? For example, `verify(statement).setInt(1, 5)` instead of `verify(statement).setInt(1, Level.TRACE.ordinal())`. I would prefer that these test will fail in future, if anyone will change the order of the severity levels in the enum class `Level` . However, I assume you have to reverse the entries in `Level` to get the expected integer values as described in #111.
2) Could you add a test case for the format pattern "level-code" in `FormatPatternParser.java` to ensure that it resolves correctöy?

**Comment by sezinkarli** [comment]
Completed the changes but seems like I've a problem with travis-ci

**Comment by pmwmedia** [comment]
> Completed the changes but seems like I've a problem with travis-ci

It seems there was a Travis internal error with the second build job. However, it works again now.

May I ask you for a last change and to replace `LEVEL_COUNT` by `Level.OFF.ordinal()`? Afterwards I will merge your pull request.

**Comment by sezinkarli** [comment]
Sure, added that as well.

**Comment by pmwmedia** [comment]
@sezinkarli Thank you very much :-) I will merge your pull request now.

**Pull request merged**
