### PR TITLE
Less strict code of the TinylogLoggingProvider #168.

### PR DESCRIPTION
**Pull request by Git5000**
### Description

Implementation of the changes discussed in issue #168.

- Moved the writer generation code from `ConfigurationParser` into the non static, non final class `TinylogLoggingConfiguration` to allow other providers to use it.
- Moved commonly useful methods like log entry handling from `TinylogLoggingProvider` into the non static, non final class `TinylogLoggingConfiguration`
- Contrary to the initial suggestion did not change the static code of `ConfigurationParser` as it now just calls static methods of Configuration. So static is ok.
- Some smaller methods are kept in `TinylogLoggingProvider` (like level calculation) as this will be used inside the logging write  itself and might affect the performance (all other changes are constructor only changes). Can be discussed but I think it is ok to keep it in its original place.
- Added new unit tests to cover these changes
- It could be discussed as idea (but I decided not to follow it for the moment) to put other access function to `Configuration` elements (e.g. filename) which is done by the writers constructors or support methods into `ConfigurationParser`  as the parser now more or less translates string elements of `Configuration`  into method getters. Similar functions might be `getFilename()`  and alike from the writers. I did not follow this up as it can also be argued that there is not so much common or usefull stuff to justify it and the writers know themself best what they are doing. So here just as possibility.

As result you can now more easily duplicate/write an own logging provider with similar functionality to `TinylogLoggingProvider` and use the helper functions from `TinylogLoggingConfiguration`. Much less code duplication is now needed.

Linked issue: #168 

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Code style follows the tinylog standard
- [x] All classes and methods have Javadoc
- [x] Changes are covered by JUnit tests including corner cases, errors, and exception handling
- [x] Maven build works including compiling, tests, and checks (`mvn verify`)
- [x] Changes are committed by a verified email address that is assigned to the GitHub account (https://github.com/settings/emails)

### Documentation

Additions or amendments for the [public documentation](https://github.com/pmwmedia/tinylog/wiki/Documentation):

```markdown
No changed to documentation.
```

### Agreements

- [x] I agree that my changes will be published under the terms of the [Apache License 2.0](https://github.com/pmwmedia/tinylog/blob/v2.0/license.txt)
- [x] I agree that my GitHub user name will be published in the release notes

### CODE REVIEW

**Comment by Git5000** [comment]
About the javadoc: `<javadocExecutable>${java.home}/bin/javadoc</javadocExecutable>`
Maybe you can leave it in the pom file commented out or mention it in the compilation instruction. If a build does not work with a user, it is much harder to find  what command to add than to delete a command.

**Comment by Git5000** [comment]
We need WritingThead visibility to be public not package to allow providers to use it ouside tinylogs core package.

**Comment by Git5000** [comment]
Btw since we have now 3 instead of 2 commits ... :-) I will make another pull request if all is ok.

**Comment by pmwmedia** [comment]
> About the javadoc: `<javadocExecutable>${java.home}/bin/javadoc</javadocExecutable>` Maybe you can leave it in the pom file commented out or mention it in the compilation instruction. If a build does not work with a user, it is much harder to find what command to add than to delete a command.

I fully agree!

> Btw since we have now 3 instead of 2 commits ... :-) I will make another pull request if all is ok.

Multiple commits are really no problem. There can be an unlimited number of commits in a single pull request. Actually, I prefer multiple small commits instead of a single big one. You don't need to create another pull request as long as all commits are about the same topic.

**Comment by pmwmedia** [comment]
@Git5000 Is this pull request ready for review?

**Comment by Git5000** [comment]
Yes it is ready. It is mainly the same files as in the other open pull request but without the merge commit and I fixed the five or six review comments which you had. The last commit is the public/private as discussed above. Mainly please have another look at the indenting whether that is ok now.

**Review by pmwmedia — APPROVED** [review]

**Comment by pmwmedia** [comment]
Thank you! Looks perfect :)

**Pull request merged**
