### PR TITLE
Support for building bleeding-edge Tinylog via JitPack

### PR DESCRIPTION
**Pull request by f4lco**
By default, JitPack builds with Java 8, which is below the minimum required version for Tinylog (9). For more information on how to retrieve artifacts from JitPack, refer to https://jitpack.io/#tinylog-org/tinylog.

This allowed me to trivially test out my fix from a bug-fix branch in a consumer project. No need for deployment in the Maven local repository, or to invent new version numbers. This escapes "it works on my machine". An example dependency coordinate would be `com.github.f4lco.tinylog:slf4j-tinylog:4ce0fb5991d05642809f9257c37ac87197474734`.

There is only one minor catch: it may take JitPack longer to build and package the software than your configured socket read time out. It means the network request for the JAR might appear to hang until the Maven build on the JitPack remote machine completes. Either one increases the socket read timeout for Maven / Gradle, or one just tries a second time hoping that the build has completed by that time. This is of course only a one-time occurrence. Once a particular commit is built, JitPack reuses the same artifact for answering subsequent requests.

### Description

Linked issue: (none)

### Definition of Done

- [x] I read [contributing.md](./contributing.md)
- [x] There are no TODOs left in the code
- [x] ~~Code style follows the tinylog standard~~
- [x] ~~All classes and methods have Javadoc~~
- [x] ~~Changes are covered by JUnit tests including edge cases, errors, and exception handling~~
- [x] Maven build works including compiling, tests, and checks (`mvn verify`)
- [x] Changes are committed by a verified email address that is assigned to the GitHub account (https://github.com/settings/emails)

### Documentation

Additions or amendments for the [public documentation](https://github.com/pmwmedia/tinylog/wiki/Documentation):

```markdown
Users can retrieve bleeding edge Tinylog versions by using [JitPack](https://jitpack.io/#tinylog-org/tinylog) by specifying commit IDs as version numbers.
```

### Agreements

- [x] I agree that my changes will be published under the terms of the [Apache License 2.0](https://github.com/pmwmedia/tinylog/blob/v2.0/license.txt) (mandatory)
- [x] I agree that my GitHub user name will be published in the release notes (optional)

### CODE REVIEW

**Comment by pmwmedia** [comment]
Yes, the Code coverage report does not make any sense here. However, the codecov bot posts a Code coverage report for each pull request automatically.

I have noticed that JitPack uses the default profile for building the Maven artifacts. Is there any way to tell JitPack to use the release profile? The correct build command would be `mvn clean install -DskipTests -P release`. The disadvantage of the default dev profile is that the created artifacts will require Java 9 and break support for Java 6-8 and Android.

**Comment by f4lco** [comment]
> I have noticed that JitPack uses the default profile for building the Maven artifacts. Is there any way to tell JitPack to use the release profile? The correct build command would be mvn clean install -DskipTests -P release. The disadvantage of the default dev profile is that the created artifacts will require Java 9 and break support for Java 6-8 and Android.

That's good to know, I fixed that. JitPack allows to override the build command within the config file. However, now I got a build failure: it claims there is a checkstyle violation. How come?
```
[INFO] --- maven-checkstyle-plugin:3.1.2:check (default) @ tinylog-api ---
[INFO] There is 1 error reported by Checkstyle 8.41 with /home/jitpack/build/configuration/checkstyle-rules.xml ruleset.
[ERROR] src/test/java/org/tinylog/configuration/FirstDummyConfigurationLoader.java:[1] (javadoc) JavadocPackage: Missing package-info.java file.
```
https://jitpack.io/com/github/f4lco/tinylog/9f36a70662853b17a96e4103c23c6a84766c0201/build.log

Do you have a toggle for disabling style checks? Or should I try to add the file? Is something wrong with the plugin (configuration)?

**Comment by pmwmedia** [comment]
Actually, I don't understand the Checkstyle violation. It does neither appear on my local machine nor on GitHub Actions. The `package-info.java` does exist in `src/main/java/org/tinylog/configuration`. Creating a duplicate in `src/test/java/org/tinylog/configuration` should trigger a compile error as there would be two `package-info.java` files for the same package.

However, I think we should disable Checkstyle and SpotBugs for JitPack as I would prefer Maven artifacts for any buildable commit, regardless if there are any kind of violations.

You can disable both via properties: `mvn clean install -DskipTests -Dcheckstyle.skip -Dspotbugs.skip -P release`

**Comment by f4lco** [comment]
Thanks, somehow that's still not really working. I need to investigate more, please do not merge at the time. I also lack a reproduction of the errors on my machine.

**Comment by f4lco** [comment]
OK the current state works now. But I'm really confused: I added `mvn -version` to the build instructions, and it showed:

> Running install command:
mvn -version;mvn clean install -DskipTests -Dcheckstyle.skip -Dspotbugs.skip -Dmaven.javadoc.skip -P release
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T19:00:29Z)
Maven home: /opt/apache-maven-3.6.1
**Java version: 10, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-10**
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.14.63-xxxx-std-ipv6-64", arch: "amd64", family: "unix"
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2

https://jitpack.io/com/github/f4lco/tinylog/7a5dd576f30af38e82e5e689174c543b6d40142b/build.log

which is not really the desired outcome after I specified `openjdk9` (see [JitPack docs](https://jitpack.io/docs/BUILDING/#java-version)). Also, the suggested alternative to use SDKMAN to pick a Java version does not work ([example](https://jitpack.io/com/github/f4lco/tinylog/05f3a7a9370b963462eeef5e257d7d72251bdf0e/build.log)). I don't know what I'm doing wrong. Maybe the easiest explanation would be that JitPack has discontinued support for both, Java 9 and SDKMAN, without updating the docs.

So, you might decide to either pick the current state (building with Java 10 while having a couple of plugins deactivated), or to scrap it. I'd lean towards scrapping - it is of not much help in advertising JitPack for this particular project and then letting it do very surprising things. How unfortunate that I was believing this service was working correctly.

**Comment by pmwmedia** [comment]
The behavior of JitPack sounds indeed not really reliable. Especially when even documented features doesn't work as documented. If they discontinue JDK 9, they should at least output a warning and update the documentation. Therefore, I will follow your advise and close this pull request without merging. Nevertheless, thank you for investing such much time for trying to make it working for tinylog.

**Pull request closed without merging**
