### PR TITLE
Implementation of Multiple LoggingProvider entries in configuration #166

### PR DESCRIPTION
**Pull request by Git5000**
#166.

### Description

Implementation of multiple logging providers as specified in issue #166. Logging providers can be given in the configuration file using `provider = a,b, c.` (ie with or without whitespace). Names will be trimmed. Empty names lead to an warning. No providers lead to the same errror as before.

Linked issue: #166 

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Code style follows the tinylog standard
- [x] All classes and methods have Javadoc
- [x] Changes are covered by JUnit tests including corner cases, errors, and exception handling
- [x] Maven build works including compiling, tests, and checks (`mvn verify`)
- [x] Changes are committed by a verified email address that is assigned to the GitHub account (https://github.com/settings/emails)

### Documentation

Additions or amendments for the [public documentation](https://github.com/pmwmedia/tinylog/wiki/Documentation):

```markdown
Documentation needs update for above comma separated provider list.
```

### Agreements

- [x] I agree that my changes will be published under the terms of the [Apache License 2.0](https://github.com/pmwmedia/tinylog/blob/v2.0/license.txt)
- [x] I agree that my GitHub user name will be published in the release notes

### CODE REVIEW

**Comment by Git5000** [comment]
Please check whether you like the error and warning messages. They of course can be changed if you provide a better text.

**Comment by Git5000** [comment]
Can you see what the actual error in the CI build is?

**Comment by pmwmedia** [comment]
> Can you see what the actual error in the CI build is?

There seems to be an internal Travis problem with downloading the OpenJDK 9. Nothing we both can do anything about. However, the Oracle JDK build works still fine. So, your code is working :-)

**Review by pmwmedia — APPROVED** [review]

**Comment by pmwmedia** [comment]
Thank you! Perfect pull request 🥇

**Pull request merged**
